# Makefile for CS154 Project 4: Building a Shell
# with hacking from Gordon Kindlmann and previous cs154 TAs,
# relative to what the textbook authors provide

DRIVER = ./sdriver.pl
TSH = ./tsh
TSHREF = ./tshref
TSHARGS = "-p"
CC = gcc
CFLAGS = -Wall -O2 -m32
FILES = $(TSH) ./myspin ./mysplit ./mystop ./myint

all: $(FILES)

##################
# run all tests
# Note: this target used to be called "tests", but that was unfortunately
# also matched by the new generalized "test%" target.
##################
alltest: $(foreach N,01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16,test$(N))

##################
# Regression tests
##################

# Run tests using the student's shell program
# The "echo" commands are just to make visual separators
# when running "make tests", first between diferent tests
# and then between the test output, and the diff to the reference
# The "$(subst test,,$@)" and "$(subst rtest,,$@)" are the test number
test%: rtest%
	@echo "======================================================================="
	$(DRIVER) -t trace$(subst test,,$@).txt -s $(TSH) -a $(TSHARGS) | tee trace$(subst test,,$@).out
	@echo "--------------------------------"
	diff rtest$(subst test,,$@) trace$(subst test,,$@).out | cat -

# Run the tests using the reference shell program
rtest%:
	$(DRIVER) -t trace$(subst rtest,,$@).txt -s $(TSHREF) -a $(TSHARGS) | tee rtest$(subst rtest,,$@)

# clean up
clean:
	rm -f $(FILES) *.o *~ rtest?? trace??.out


# The tshref.out file was generated by
# make clean; make; cp tshref tsh; make alltest > tshref.out
